export const ERROR_CODES = {
  FORECAST: "FORECAST_FAILED",
  GEOCODING: "GEOCODING_FAILED",
  SEARCH: "SEARCH_FAILED",
  REQUEST_DATA: "INVALID_REQUEST_DATA",
  INTERNAL: "INTERNAL_SERVER_ERROR",
  AI_DESCRIPTION: "AI_DESCRIPTION_FAILED",
  RATE_LIMIT: "RATE_LIMIT_EXCEEDED",
  UNKNOWN: "UNKNOWN_ERROR",
  VALIDATION: "VALIDATION_ERROR",
  TIMEOUT: "TIMEOUT_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
